blivedm:
    server: ws://blivechat:12450/api/chat
    roomid: 26949229
textouthttp:
    server: ""
    droprate: 0
live2d:
    driver: http://live2ddriver:9004/driver
    forwarder: http://live2ddriver:9002/live2d
chatbot:
    musharing:
        server: musharing_chatbot:50051
        disabled: false
    chatgpt:
        server: chatgpt_chatbot:50052
        configs:
            - version: 3
              apikey: sk_xxx
              initialprompt: You are muli, an AI VTuber live streaming.
        cooldown: 15
        disabled: false
sayer:
    server: externalsayer:50010
    role: default
listen:
    textinhttp: 0.0.0.0:51080
    audiocontrollerws: 0.0.0.0:51081
readdm: true
reduceduration: 5
toolong:
    maxwords: 500
    quibbles:
        - 太长了，不想说。
        - 禁則事項です。
        - 爬。
